config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks do
    member do
      put :complete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: "Task created successfully" }
        format.js
      else
        format.html { render :new, notice: @task.errors.full_messages }
      end
    end
  end

  def index
    @completed_tasks = Task.where(completed: true)
    @incomplete_tasks = Task.where(completed:false)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, danger: "Task deleted successfully" }
        format.js
      else
        format.html { render :edit, notice: @task.errors.full_messages }
      end
    end
  end

  def complete
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.completed?
        @task.update_attributes(completed: false)
        format.html { redirect_to root_path }
        format.js
      else
        @task.update_attributes(completed: true)
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  def destroy
    @task = Task.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to root_path, danger: "Task deleted successfully" }
      format.js
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

  def completed_text(task)
    return "Mark incomplete" if task.completed
    "Mark completed"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header sticky-top bg-light p-2 mb-2 text-center"><h3>Todo list</h3></div>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: "alert alert-info" %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
  <%= form_for @task, :html => {class: "form-inline"}, remote: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title:", class: "p-2" %>
        <%= f.text_field :title, class: "form-control" %></br>
      </div>

      <div class="form-group">
        <%= f.label :description, "Description:", class: "p-2" %>
        <%= f.text_field :description, class: "form-control mr-2" %></br>
      </div>

      <div class="form-group">
        <%= f.submit  class: "btn btn-primary btn-sm" %>
        <button class="cancel-create-btn btn btn-sm">Cancel</button>
      </div>
  <% end %>

app/views/tasks/_task.html.erb
<li class="item-<%= task.id %> list-group-item mb-3 task-item-cont p-2">
  <div class="card-<%= task.id %> d-flex flex-wrap">
    <div class="info mr-auto ">
      <h5 class="card-title mb-0"><%= task.title %></h4>
      <p class="mb-0"><%= task.description %></p>
    </div>
    <%= form_for task, :html => {:class => 'float-sm-right'}, remote: true do |f| %>
      <%= link_to "Edit", edit_task_path(task), class: "btn btn-outline-primary btn-sm", remote: true %>
      <%= link_to completed_text(task), complete_task_path(task), class: "mark-comp btn btn-outline-primary btn-sm", method: :put, remote: true %>
      <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-outline-danger btn-sm', remote: true %>
    <% end %>
  </div>
</li>

app/views/tasks/complete.js.erb
$('.item-<%=@task.id%>').replaceWith('<%= j render(@task) %>')
<% if @task.completed? %>
  $('.item-<%=@task.id%>').appendTo('.completed-tasks-list')
<% else %>
  $('.item-<%=@task.id%>').appendTo('.incomplete-tasks-list')
<% end %>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_task_link').show();
$('.incomplete-tasks-list').append('<%= j render(@task) %>')
$('.item-<%=@task.id%>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('.item-<%=@task.id%>').remove();

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>
<%= render 'form' %>

app/views/tasks/edit.js.erb
$('.card-<%=@task.id%>').append('<%= j render 'form' %>');
$('#edit_task_<%=@task.id%>').remove();

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="new_task_cont d-flex col-sm justify-content-between">
      <%= link_to new_task_path, id: 'new_task_link', class: 'btn btn-success', remote: true do %>
        <i class="glyphicon glyphicon-plus"></i> New task
      <% end %>
      <button class="comp-toggle btn btn-info">Toggle completed</button>
    </div>
  </div>

  <div class="row">
    <ul class="incomplete-tasks-list list-group w-100">
      <div class="row">
        <h5 class="incomplete-toggle col-sm mt-3">Task list</h3>
      </div>
      <% @incomplete_tasks.each do |task| %>
        <%= render :partial => task %>
      <% end %>
    </ul>

    <div class="completed-tasks-list list-group w-100" style="display:none;">
      <div class="row">
        <h5 class="complete-toggle col-sm mt-3">Completed tasks</h3>
      </div>
      <% @completed_tasks.each do |task| %>
        <%= render :partial => task %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>
<%= render 'form' %>

app/views/tasks/new.js.erb
$('#new_task_link').hide().after('<%= j render 'form' %>')
$('.cancel-create-btn').click(function() {
  $('#new_task').remove();
  $('#new_task_link').show();
})

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<%= link_to "Edit task", edit_task_path(@task), class: 'btn btn-info btn-xs' %>
<%= link_to "Delete task", @task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs', remote: true %>
<p><%= @task.description %></p>
<span><%= @task.completed %></span>

app/views/tasks/update.js.erb
$('.item-<%=@task.id%>').replaceWith('<%= j render(@task) %>')